# Generated by Django 5.1.7 on 2025-03-20 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nume')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Adresa')),
                ('customer_city', models.CharField(max_length=100, verbose_name='Oras')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clienti',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Producator')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Disponible device',
                'verbose_name_plural': 'Disponible devices',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial number')),
                ('owner', models.CharField(max_length=255, verbose_name='Owner')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='orders_app.customer', verbose_name='Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instances', to='orders_app.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device in field',
                'verbose_name_plural': 'Devices in field',
                'db_table': 'device_in_field',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(verbose_name='Order description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('order_status', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed'), ('Need info', 'Need info'), ('Open', 'Open')], max_length=20, verbose_name='Order status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders_app.customer', verbose_name='Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders_app.deviceinfield', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comenzi',
                'db_table': 'orders',
            },
        ),
    ]
